// === Game data (CROPS, HERBS, TREES, ANIMALS, RES_INFO, BUILDINGS, UPGRADES, ANIMAL_FEED, etc.) — extracted from farmvalley.html ===

// ===== DATA: [name, emoji, stageTime(s), cost, sellValue, xp, reqLevel] =====
var N=0,E=1,ST=2,CO=3,SV=4,XP=5,RL=6;
var CROPS=[
['Carotte','<img src="farmvalley_imgs/carotte.svg" class="plant-img">',3,5,15,5,1],['Tomate','<img src="farmvalley_imgs/tomate.svg" class="plant-img">',6,8,22,8,1],['Salade','<img src="farmvalley_imgs/salade.svg" class="plant-img">',10,12,32,12,2],
['Poivron','<img src="farmvalley_imgs/poivron.svg" class="plant-img">',16,16,45,16,2],['Blé','<img src="farmvalley_imgs/ble.svg" class="plant-img">',22,20,58,20,3],['Concombre','<img src="farmvalley_imgs/concombre.svg" class="plant-img">',30,25,72,25,3],
['Maïs','<img src="farmvalley_imgs/mais.svg" class="plant-img">',40,30,88,30,4],['Aubergine','<img src="farmvalley_imgs/aubergine.svg" class="plant-img">',55,38,110,38,5],['P.de terre','<img src="farmvalley_imgs/pdterre.svg" class="plant-img">',70,46,135,46,6],
['Fraise','<img src="farmvalley_imgs/fraise.svg" class="plant-img">',90,55,165,55,7],['Piment','<img src="farmvalley_imgs/piment.svg" class="plant-img">',110,65,200,65,8],['Oignon','<img src="farmvalley_imgs/oignon.svg" class="plant-img">',135,78,240,78,9],
['Brocoli','<img src="farmvalley_imgs/brocoli.svg" class="plant-img">',165,92,290,92,10],['Melon','<img src="farmvalley_imgs/melon.svg" class="plant-img">',200,110,350,110,11],['Pastèque','<img src="farmvalley_imgs/pasteque.svg" class="plant-img">',240,130,420,130,12],
['Champignon','<img src="farmvalley_imgs/champignon.svg" class="plant-img">',290,155,500,155,14],['Ail','<img src="farmvalley_imgs/ail.svg" class="plant-img">',350,185,600,185,16],['Cerise','<img src="farmvalley_imgs/cerise.svg" class="plant-img">',420,220,720,220,17],
['Citrouille','<img src="farmvalley_imgs/citrouille.svg" class="plant-img">',550,270,870,270,18],['Fleur dorée','<img src="farmvalley_imgs/fleur_doree.svg" class="plant-img">',1100,350,1500,400,20],
['Radis','<img src="farmvalley_imgs/radis.svg" class="plant-img">',8,7,20,7,1],['Épinards','<img src="farmvalley_imgs/epinards.svg" class="plant-img">',14,14,40,14,2],['Petits pois','<img src="farmvalley_imgs/petits_pois.svg" class="plant-img">',18,18,50,18,3],
];
var HERBS=[['Basilic','<img src="farmvalley_imgs/basilic.svg" class="plant-img">',8,10,28,10,2],['Persil','<img src="farmvalley_imgs/persil.svg" class="plant-img">',12,15,40,15,3],['Thym','<img src="farmvalley_imgs/thym.svg" class="plant-img">',18,25,65,25,5],['Camomille','<img src="farmvalley_imgs/camomille.svg" class="plant-img">',30,45,120,45,8],['Sauge','<img src="farmvalley_imgs/sauge.svg" class="plant-img">',45,65,170,65,10],['Origan','<img src="farmvalley_imgs/origan.svg" class="plant-img">',60,85,220,85,12],['Menthe','<img src="farmvalley_imgs/menthe.svg" class="plant-img">',250,160,520,160,13],['Coriandre','<img src="farmvalley_imgs/coriandre.svg" class="plant-img">',80,110,290,110,14],['Lavande','<img src="farmvalley_imgs/lavande.svg" class="plant-img">',300,200,650,200,15],['Romarin','<img src="farmvalley_imgs/romarin.svg" class="plant-img">',320,240,780,240,16],['Citronnelle','<img src="farmvalley_imgs/citronnelle.svg" class="plant-img">',120,300,950,300,18],['Verveine','<img src="farmvalley_imgs/verveine.svg" class="plant-img">',150,380,1200,380,20],['Mélisse','<img src="farmvalley_imgs/melisse.svg" class="plant-img">',180,480,1500,480,22]];
var TREES=[
['Pommier','<img src="farmvalley_imgs/pommier.svg" class="plant-img">',90,200,400,100,3],['Poirier','<img src="farmvalley_imgs/poirier.svg" class="plant-img">',130,300,600,150,5],['Abricotier','<img src="farmvalley_imgs/abricotier.svg" class="plant-img">',160,380,750,180,6],['Oranger','<img src="farmvalley_imgs/oranger.svg" class="plant-img">',180,450,900,220,7],
['Prunier','<img src="farmvalley_imgs/prunier.svg" class="plant-img">',200,520,1050,260,8],['Citronnier','<img src="farmvalley_imgs/citronnier.svg" class="plant-img">',240,600,1200,300,9],['Figuier','<img src="farmvalley_imgs/figuier.svg" class="plant-img">',270,700,1400,340,10],['Bananier','<img src="farmvalley_imgs/bananier.svg" class="plant-img">',310,800,1600,400,11],
['Grenadier','<img src="farmvalley_imgs/grenadier.svg" class="plant-img">',350,950,1900,460,12],['P\u00eacher','<img src="farmvalley_imgs/pecher.svg" class="plant-img">',400,1100,2200,530,13],['Avocatier','<img src="farmvalley_imgs/avocatier.svg" class="plant-img">',450,1300,2600,620,14],
['Manguier','<img src="farmvalley_imgs/manguier.svg" class="plant-img">',500,1500,3000,700,15],['Kiwi','<img src="farmvalley_imgs/kiwi.svg" class="plant-img">',560,1750,3500,800,16],['Vigne','<img src="farmvalley_imgs/vigne.svg" class="plant-img">',620,2000,4000,900,17],
['Papayer','<img src="farmvalley_imgs/papayer.svg" class="plant-img">',680,2400,4800,1050,18],['Noyer','<img src="farmvalley_imgs/noyer.svg" class="plant-img">',720,2600,5200,1120,19],['Cocotier','<img src="farmvalley_imgs/cocotier.svg" class="plant-img">',750,2800,5600,1200,19],
['Ch\u00e2taignier','<img src="farmvalley_imgs/chataignier.svg" class="plant-img">',800,3200,6500,1380,21],['Olivier','<img src="farmvalley_imgs/olivier.svg" class="plant-img">',900,3800,7800,1600,20],['Litchi','<img src="farmvalley_imgs/litchi.svg" class="plant-img">',850,3500,7200,1500,22]];
var ANIMALS=[
['Poule','<img src="farmvalley_imgs/poule.svg" class="plant-img">',30,800,1100,150,5],['Canard','<img src="farmvalley_imgs/canard.svg" class="plant-img">',40,1000,1400,200,5],['Lapin','<img src="farmvalley_imgs/lapin.svg" class="plant-img">',50,1300,1850,280,6],
['Mouton','<img src="farmvalley_imgs/mouton.svg" class="plant-img">',65,1700,2400,370,7],['Chèvre','<img src="farmvalley_imgs/chevre.svg" class="plant-img">',80,2200,3100,480,8],['Cochon','<img src="farmvalley_imgs/cochon.svg" class="plant-img">',95,2800,4000,600,9],
['Vache','<img src="farmvalley_imgs/vache.svg" class="plant-img">',115,3500,5100,750,10],['Cheval','<img src="farmvalley_imgs/cheval.svg" class="plant-img">',135,4400,6500,930,11],['Abeille','<img src="farmvalley_imgs/abeille.svg" class="plant-img">',155,5500,8200,1150,12],
['Dinde','<img src="farmvalley_imgs/dinde.svg" class="plant-img">',180,6800,10000,1400,13],['Alpaga','<img src="farmvalley_imgs/alpaga.svg" class="plant-img">',205,8500,12500,1700,14],['Paon','<img src="farmvalley_imgs/paon.svg" class="plant-img">',235,10500,15500,2100,15],
['Cygne','<img src="farmvalley_imgs/cygne.svg" class="plant-img">',265,13000,19500,2600,16],['Flamant','<img src="farmvalley_imgs/flamant.svg" class="plant-img">',300,16000,24000,3200,17],['Perroquet','<img src="farmvalley_imgs/perroquet.svg" class="plant-img">',340,20000,30000,4000,18],
['Hibou','<img src="farmvalley_imgs/hibou.svg" class="plant-img">',380,25000,38000,5000,18],['Tortue','<img src="farmvalley_imgs/tortue.svg" class="plant-img">',420,31000,47000,6200,19],['Dauphin','<img src="farmvalley_imgs/dauphin.svg" class="plant-img">',470,40000,60000,8000,19],
['Panda','<img src="farmvalley_imgs/panda.svg" class="plant-img">',530,52000,78000,10000,20],['Licorne','<img src="farmvalley_imgs/licorne.svg" class="plant-img">',600,70000,110000,15000,20],['Saumon','<img src="farmvalley_imgs/saumon.svg" class="plant-img">',350,18000,27000,2000,14],['Autruche','<img src="farmvalley_imgs/autruche.svg" class="plant-img">',400,22000,33000,2500,16],['Pintade','<img src="farmvalley_imgs/pintade.svg" class="plant-img">',300,15000,22000,1800,13],
['Renard','<img src="farmvalley_imgs/renard.svg" class="plant-img">',650,90000,135000,18000,21],['Cerf','<img src="farmvalley_imgs/cerf.svg" class="plant-img">',750,120000,180000,23000,23],['Paon blanc','<img src="farmvalley_imgs/paon_blanc.svg" class="plant-img">',850,160000,245000,29000,25],['Ph\u00e9nix','<img src="farmvalley_imgs/phenix.svg" class="plant-img">',950,230000,350000,42000,27],['Dragon','<img src="farmvalley_imgs/dragon.svg" class="plant-img">',1100,320000,500000,65000,30]];
var ITEMS=[CROPS,HERBS,TREES,ANIMALS];
var CAT_WATER=[3,3,4,5];
var CAT_NAMES=['Cultures','Herbes','Arbres','Animaux'];
var CAT_ICONS=['🌱','🌿','🌳','🐄'];
var MYSTERY_COSTS=[0,0,0,0];
function calcMysteryCosts(){for(var c=0;c<4;c++){var arr=ITEMS[c],sum=0;for(var i=0;i<arr.length;i++)sum+=arr[i][CO];MYSTERY_COSTS[c]=Math.round(sum/arr.length);}}
function getMysteryCost(cat){if(cat<0||cat>3)return MYSTERY_COSTS[0];return MYSTERY_COSTS[cat]}
var UPGRADES=[
{id:'speed',name:'Engrais rapide',desc:'-5% temps/niv',icon:'⚡',base:30,mult:1.15,max:200,group:'engrais'},
{id:'bspeed',name:'Engrais atelier',desc:'-5% temps atelier/niv',icon:'🏭',base:30,mult:1.15,max:200,group:'engrais'},
{id:'animalspeed',name:'Engrais animaux',desc:'-5% temps animal/niv',icon:'🐾',base:30,mult:1.15,max:200,group:'engrais'},
{id:'autoharvest',name:'Auto-récolte',desc:'Récolte auto (40s-20 min)',icon:'🤖',base:300,mult:2.5,max:30,group:'auto'},
{id:'autowater',name:'Auto-arrosage',desc:'Arrose auto (40s-20 min)',icon:'🚿',base:400,mult:2.5,max:30,group:'auto'},
{id:'autoatelier',name:'Auto-atelier',desc:'Récolte ateliers auto (40s-20 min)',icon:'🛠️',base:400,mult:2.5,max:30,group:'auto'},
{id:'autofeed',name:'Auto-alimentation',desc:'Nourrit animaux auto (40s-20 min)',icon:'🍽️',base:400,mult:2.5,max:30,group:'auto'},
{id:'animalslots',name:'Parcelles animaux',desc:'+2 emplacements animaux/niv',icon:'🐄',base:500,mult:1.3,max:49,group:'parcelles'},
{id:'watermax',name:'Réservoir',desc:'+10 eau max (→100000)',icon:'🪣',base:15,mult:1.03,max:9990,group:'parcelles'},
{id:'value',name:'Meilleur marché',desc:'+15% vente/niv',icon:'💎',base:40,mult:2.0,max:100,group:'autre'},
{id:'animalvalue',name:'Quantité animaux',desc:'+1 ressource animal/niv',icon:'🥚',base:80,mult:1.6,max:50,group:'autre'},
{id:'savingsrate',name:'Taux d\'épargne',desc:'Intérêt mensuel: 0.2%→10%',icon:'🏦',base:10000,mult:2.2,max:50,group:'autre'},
{id:'distillateur',name:'Distillateur',desc:'+1 produit/recette herbes/niv',icon:'⚗️',base:5000,mult:2.0,max:10,group:'autre'}];
var UPG_GROUPS=[{id:'engrais',label:'⚡ Engrais'},{id:'auto',label:'🤖 Automatisations'},{id:'parcelles',label:'🔲 Parcelles & Capacité'},{id:'autre',label:'💎 Autre'}];
var WATER_PACKS=[[10,20,'10💧'],[30,50,'30💧'],[100,150,'100💧']];

// ===== ANIMAL PEN =====
var ACOLS=5,AMAX=20,ATOTAL=100,ASTART=3;
// [feedRes('coins'=gold), feedQty, outputRes(null=coins), coinsPerTick]
var AF=0,AQ=1,AO=2,AC=3;
var ANIMAL_FEED=[
  ['mais',2,'oeuf',0],['ble',2,'plume',0],['carotte',2,'fourrure',0],
  ['ble',3,'laine',0],['ble',3,'lait_chevre',0],['patate',3,'viande_porc',0],
  ['ble',4,'lait',0],['carotte',5,'steak',0],['fleur',2,'miel',0],
  ['mais',4,'viande_dinde',0],['ble',4,'laine',0],['mais',4,'plume',0],
  ['ble',5,'plume_blanche',0],['fraise',5,'plume_rose',0],['banane',4,'plume_verte',0],
  ['champignon',5,'plume',0],['fraise',6,'carapace',0],  ['coins',2000,'corail',0],
  ['mangue',5,null,4500],['fleur',8,'corne_magique',0],['mais',3,'poisson',0],['ble',4,'oeuf_geant',0],['mais',3,'plume_luxe',0],
  ['abricot',4,'pelisse',0],['champignon',6,'bois_cerf',0],['fleur',8,'plume_irisee',0],['corne_magique',3,'cendre_magique',0],['steak',3,'ecaille_dragon',0]
];

// ===== RESOURCES =====
var RES_KEYS=[
  // --- Bruts (r\u00e9colt\u00e9s) ---
  'bois','lait','ble','mais','oeuf','laine',
  'pomme','fraise','lait_chevre','citron','miel','raisin','noix_coco','olive',
  'tomate','carotte','oignon','patate','champignon','citrouille','cerise','fleur',
  'poire','orange','banane','peche','mangue',
  'viande_porc','viande_dinde','plume','fourrure',
  'steak','plume_blanche','corail','plume_rose','corne_magique','plume_verte','carapace','poisson','oeuf_geant','plume_luxe',
  'pelisse','bois_cerf','plume_irisee','cendre_magique','ecaille_dragon',
  'salade','poivron','concombre','aubergine','piment','brocoli','melon','pasteque','ail',
  'radis','epinards','petits_pois','lavande','menthe','romarin','caramel',
  'basilic','persil','thym','camomille','sauge','origan','coriandre','citronnelle','verveine','melisse',
  'abricot','prune','figue','grenade','avocat','kiwi','papaye','noix','chataigne','litchi',
  // --- Transform\u00e9s ---
  'beurre','creme','farine_ble','farine_mais','sucre','fromage','jus_pomme','confiture',
  'vin','huile_olive','lait_coco','chocolat',
  'sauce_tomate','soupe','jus_orange','smoothie','marmelade','cidre',
  'charcuterie','saucisse','pizza','risotto','tarte_citrouille',
  'parfum','bougie','coussin','roti_dinde','salade_composee',
  'compote','jus_poire','jus_cerise','semoule','soupe_citrouille','ratatouille','gaspacho','soupe_brocoli','pesto_ail','pelote','tapis','fondue','raclette','brie','popcorn','pain','tortilla','brioche','muffin','steak_sauce','jus_citron','piment_confit','confiture_melon','bonbon_miel','nougat','hydromel','cocktail','jus_mangue','milkshake_fraise','confiture_cerise','vinaigre','vin_premium','sangria','ratafia','calzone','pizza_champignon','tapenade','jus_tropical','punch_exotique','sirop_piment','collier_corail','huile_tortue','tarte_fruits','croissant','macaron','tarte_caramel','flan_caramel','potion_magique','manteau_plumes','bijou_corail','parfum_lavande','bougie_romarin','sachet_herbes','truffes','fontaine_choco','brownie','mousse_choco','chocolat_caramel','soupe_poisson','fish_chips','bouillabaisse','carpaccio_marin','brochettes','festin_dinde','gigot_ail','menu_gastro','festin_royal','banquet','plateau_mer','thon_huile','tartare_marin','festin_steak','plat_magique','cape_prestige','buffet_palace','gala_ultime','banquet_ultime','festin_marin_royal','salade_fraiche','meli_melo','puree','echarpe','chapeau_plume','fromage_chevre','barbe_a_papa','gateau','crepes','pate','steak_grille','gelee','pain_epices','smoothie_peche','jus_pasteque','pizza_legumes','limonade_pasteque','aquarium_deco','plumeau_enchante','pralines','poisson_grille','poulet_roti','cotelettes','entrecote_royale','omelette_geante','diner_royal',
  'pommade','baume_levres','creme_hydratante','lotion_apaisante','masque_beaute','shampoing','gel_douche','savon','huile_lavande','huile_menthe','parfum_naturel','serum_visage',
  'tisane_relaxante','tisane_digestive','sirop_medicinal','vinaigre_aromatique','pesto_basilic','huile_aromatisee','sel_herbes','sirop_citronnelle',
  'bougie_aromatique','encens','sachet_parfume','spray_maison',
  'yaourt','glace','milkshake_abricot','fromage_blanc','jus_kiwi','smoothie_papaye','jus_grenade',
  'tarte_abricot','gateau_noix','confiture_abricot','sirop_kiwi','tapenade_figue','guacamole','compote_prune','confiture_litchi','creme_chataigne','pate_amande'];
var RES_INFO={
  eau:{name:'Eau',emoji:'💧'},
  bois:{name:'Bois',emoji:'🪵'},
  lait:{name:'Lait',emoji:'🥛',img:'<img src="farmvalley_imgs/lait.svg" class="plant-img">'},ble:{name:'Blé',emoji:'🌾',img:'<img src="farmvalley_imgs/ble.svg" class="plant-img">'},mais:{name:'Maïs',emoji:'🌽',img:'<img src="farmvalley_imgs/mais.svg" class="plant-img">'},
  oeuf:{name:'Œuf',emoji:'🥚',img:'<img src="farmvalley_imgs/oeuf.svg" class="plant-img">'},laine:{name:'Laine',emoji:'🧶',img:'<img src="farmvalley_imgs/laine.svg" class="plant-img">'},
  pomme:{name:'Pomme',emoji:'🍎',img:'<img src="farmvalley_imgs/pomme.svg" class="plant-img">'},fraise:{name:'Fraise',emoji:'🍓',img:'<img src="farmvalley_imgs/fraise.svg" class="plant-img">'},
  lait_chevre:{name:'Lait chèvre',emoji:'🐐',img:'<img src="farmvalley_imgs/lait_chevre.svg" class="plant-img">'},citron:{name:'Citron',emoji:'🍋',img:'<img src="farmvalley_imgs/citron.svg" class="plant-img">'},
  miel:{name:'Miel',emoji:'🍯',img:'<img src="farmvalley_imgs/miel.svg" class="plant-img">'},raisin:{name:'Raisin',emoji:'🍇',img:'<img src="farmvalley_imgs/raisin.svg" class="plant-img">'},
  noix_coco:{name:'Noix coco',emoji:'🥥',img:'<img src="farmvalley_imgs/noix_coco.svg" class="plant-img">'},olive:{name:'Olive',emoji:'🫒',img:'<img src="farmvalley_imgs/olive.svg" class="plant-img">'},
  tomate:{name:'Tomate',emoji:'🍅',img:'<img src="farmvalley_imgs/tomate.svg" class="plant-img">'},carotte:{name:'Carotte',emoji:'🥕',img:'<img src="farmvalley_imgs/carotte.svg" class="plant-img">'},
  oignon:{name:'Oignon',emoji:'🧅',img:'<img src="farmvalley_imgs/oignon.svg" class="plant-img">'},patate:{name:'Patate',emoji:'🥔',img:'<img src="farmvalley_imgs/pdterre.svg" class="plant-img">'},
  champignon:{name:'Champignon',emoji:'🍄',img:'<img src="farmvalley_imgs/champignon.svg" class="plant-img">'},citrouille:{name:'Citrouille',emoji:'🎃',img:'<img src="farmvalley_imgs/citrouille.svg" class="plant-img">'},
  cerise:{name:'Cerise',emoji:'🍒',img:'<img src="farmvalley_imgs/cerise.svg" class="plant-img">'},fleur:{name:'Fleur',emoji:'💐',img:'<img src="farmvalley_imgs/fleur_doree.svg" class="plant-img">'},
  poire:{name:'Poire',emoji:'🍐',img:'<img src="farmvalley_imgs/poire.svg" class="plant-img">'},orange:{name:'Orange',emoji:'🍊',img:'<img src="farmvalley_imgs/orange.svg" class="plant-img">'},
  banane:{name:'Banane',emoji:'🍌',img:'<img src="farmvalley_imgs/banane.svg" class="plant-img">'},peche:{name:'Pêche',emoji:'🍑',img:'<img src="farmvalley_imgs/peche.svg" class="plant-img">'},
  mangue:{name:'Mangue',emoji:'🥭',img:'<img src="farmvalley_imgs/mangue.svg" class="plant-img">'},
  viande_porc:{name:'Porc',emoji:'🥓',img:'<img src="farmvalley_imgs/viande_porc.svg" class="plant-img">'},viande_dinde:{name:'Dinde',emoji:'🦃',img:'<img src="farmvalley_imgs/viande_dinde.svg" class="plant-img">'},
  plume:{name:'Plume',emoji:'🪶',img:'<img src="farmvalley_imgs/plume.svg" class="plant-img">'},fourrure:{name:'Fourrure',emoji:'🐇',img:'<img src="farmvalley_imgs/fourrure.svg" class="plant-img">'},
  steak:{name:'Steak',emoji:'🥩',img:'<img src="farmvalley_imgs/steak.svg" class="plant-img">'},plume_blanche:{name:'Plume blanche',emoji:'🕊️',img:'<img src="farmvalley_imgs/plume_blanche.svg" class="plant-img">'},
  corail:{name:'Corail',emoji:'🪸',img:'<img src="farmvalley_imgs/ail.svg" class="plant-img">'},plume_rose:{name:'Plume rose',emoji:'🩷',img:'<img src="farmvalley_imgs/plume_rose.svg" class="plant-img">'},
  corne_magique:{name:'Corne magique',emoji:'🦄',img:'<img src="farmvalley_imgs/corne_magique.svg" class="plant-img">'},plume_verte:{name:'Plume verte',emoji:'🦜',img:'<img src="farmvalley_imgs/plume_verte.svg" class="plant-img">'},
  carapace:{name:'Carapace',emoji:'🐢',img:'<img src="farmvalley_imgs/carapace.svg" class="plant-img">'},poisson:{name:'Poisson',emoji:'🐟',img:'<img src="farmvalley_imgs/poisson.svg" class="plant-img">'},oeuf_geant:{name:'Œuf géant',emoji:'🥚',img:'<img src="farmvalley_imgs/oeuf_geant.svg" class="plant-img">'},plume_luxe:{name:'Plume luxe',emoji:'🦚',img:'<img src="farmvalley_imgs/plume_luxe.svg" class="plant-img">'},
  pelisse:{name:'Pelisse',emoji:'🦊',img:'<img src="farmvalley_imgs/pelisse.svg" class="plant-img">'},bois_cerf:{name:'Bois de cerf',emoji:'🦌',img:'<img src="farmvalley_imgs/bois_cerf.svg" class="plant-img">'},plume_irisee:{name:'Plume iris\u00e9e',emoji:'🪷',img:'<img src="farmvalley_imgs/plume_irisee.svg" class="plant-img">'},cendre_magique:{name:'Cendre magique',emoji:'🔥',img:'<img src="farmvalley_imgs/cendre_magique.svg" class="plant-img">'},ecaille_dragon:{name:'\u00c9caille dragon',emoji:'🐉',img:'<img src="farmvalley_imgs/ecaille_dragon.svg" class="plant-img">'},
  salade:{name:'Salade',emoji:'🥬',img:'<img src="farmvalley_imgs/salade.svg" class="plant-img">'},poivron:{name:'Poivron',emoji:'🫑',img:'<img src="farmvalley_imgs/poivron.svg" class="plant-img">'},
  concombre:{name:'Concombre',emoji:'🥒',img:'<img src="farmvalley_imgs/concombre.svg" class="plant-img">'},aubergine:{name:'Aubergine',emoji:'🍆',img:'<img src="farmvalley_imgs/aubergine.svg" class="plant-img">'},
  piment:{name:'Piment',emoji:'🌶️',img:'<img src="farmvalley_imgs/piment.svg" class="plant-img">'},brocoli:{name:'Brocoli',emoji:'🥦',img:'<img src="farmvalley_imgs/brocoli.svg" class="plant-img">'},
  melon:{name:'Melon',emoji:'🍈',img:'<img src="farmvalley_imgs/melon.svg" class="plant-img">'},pasteque:{name:'Pastèque',emoji:'🍉',img:'<img src="farmvalley_imgs/pasteque.svg" class="plant-img">'},ail:{name:'Ail',emoji:'🧄'},
  radis:{name:'Radis',emoji:'🔴',img:'<img src="farmvalley_imgs/radis.svg" class="plant-img">'},epinards:{name:'Épinards',emoji:'🌿',img:'<img src="farmvalley_imgs/epinards.svg" class="plant-img">'},petits_pois:{name:'Petits pois',emoji:'🫛',img:'<img src="farmvalley_imgs/petits_pois.svg" class="plant-img">'},
  lavande:{name:'Lavande',emoji:'💜',img:'<img src="farmvalley_imgs/lavande.svg" class="plant-img">'},menthe:{name:'Menthe',emoji:'🍃',img:'<img src="farmvalley_imgs/menthe.svg" class="plant-img">'},romarin:{name:'Romarin',emoji:'🌿',img:'<img src="farmvalley_imgs/romarin.svg" class="plant-img">'},
  basilic:{name:'Basilic',emoji:'🌿',img:'<img src="farmvalley_imgs/basilic.svg" class="plant-img">'},persil:{name:'Persil',emoji:'🌿',img:'<img src="farmvalley_imgs/persil.svg" class="plant-img">'},thym:{name:'Thym',emoji:'🌿',img:'<img src="farmvalley_imgs/thym.svg" class="plant-img">'},
  camomille:{name:'Camomille',emoji:'🌼',img:'<img src="farmvalley_imgs/camomille.svg" class="plant-img">'},sauge:{name:'Sauge',emoji:'🍃',img:'<img src="farmvalley_imgs/sauge.svg" class="plant-img">'},origan:{name:'Origan',emoji:'🌿',img:'<img src="farmvalley_imgs/origan.svg" class="plant-img">'},
  coriandre:{name:'Coriandre',emoji:'🌿',img:'<img src="farmvalley_imgs/coriandre.svg" class="plant-img">'},citronnelle:{name:'Citronnelle',emoji:'🍋',img:'<img src="farmvalley_imgs/citronnelle.svg" class="plant-img">'},verveine:{name:'Verveine',emoji:'🌿',img:'<img src="farmvalley_imgs/verveine.svg" class="plant-img">'},melisse:{name:'M\u00e9lisse',emoji:'🌿',img:'<img src="farmvalley_imgs/melisse.svg" class="plant-img">'},
  abricot:{name:'Abricot',emoji:'🍑',img:'<img src="farmvalley_imgs/abricot.svg" class="plant-img">'},prune:{name:'Prune',emoji:'🫐',img:'<img src="farmvalley_imgs/prune.svg" class="plant-img">'},figue:{name:'Figue',emoji:'🍈',img:'<img src="farmvalley_imgs/figue.svg" class="plant-img">'},
  grenade:{name:'Grenade',emoji:'🍎',img:'<img src="farmvalley_imgs/grenade.svg" class="plant-img">'},avocat:{name:'Avocat',emoji:'🥑',img:'<img src="farmvalley_imgs/avocat.svg" class="plant-img">'},kiwi:{name:'Kiwi',emoji:'🥝',img:'<img src="farmvalley_imgs/fruit_kiwi.svg" class="plant-img">'},
  papaye:{name:'Papaye',emoji:'🍈',img:'<img src="farmvalley_imgs/papaye.svg" class="plant-img">'},noix:{name:'Noix',emoji:'🌰',img:'<img src="farmvalley_imgs/noix.svg" class="plant-img">'},chataigne:{name:'Ch\u00e2taigne',emoji:'🌰',img:'<img src="farmvalley_imgs/chataigne.svg" class="plant-img">'},litchi:{name:'Litchi',emoji:'🍇',img:'<img src="farmvalley_imgs/fruit_litchi.svg" class="plant-img">'},
  caramel:{name:'Caramel',emoji:'🍮',img:'<img src="farmvalley_imgs/caramel.svg" class="plant-img">'},
  beurre:{name:'Beurre',emoji:'🧈',img:'<img src="farmvalley_imgs/beurre.svg" class="plant-img">'},creme:{name:'Crème',emoji:'🍦',img:'<img src="farmvalley_imgs/creme.svg" class="plant-img">'},
  farine_ble:{name:'Farine blé',emoji:'🌾',img:'<img src="farmvalley_imgs/farine_ble.svg" class="plant-img">'},farine_mais:{name:'Farine maïs',emoji:'🌽',img:'<img src="farmvalley_imgs/farine_mais.svg" class="plant-img">'},
  sucre:{name:'Sucre',emoji:'🍬',img:'<img src="farmvalley_imgs/sucre.svg" class="plant-img">'},fromage:{name:'Fromage',emoji:'🧀',img:'<img src="farmvalley_imgs/fromage.svg" class="plant-img">'},
  jus_pomme:{name:'Jus pomme',emoji:'🧃',img:'<img src="farmvalley_imgs/jus_pomme.svg" class="plant-img">'},confiture:{name:'Confiture',emoji:'🫙',img:'<img src="farmvalley_imgs/confiture.svg" class="plant-img">'},
  vin:{name:'Vin',emoji:'🍷',img:'<img src="farmvalley_imgs/vin.svg" class="plant-img">'},huile_olive:{name:'Huile olive',emoji:'🫗',img:'<img src="farmvalley_imgs/huile_olive.svg" class="plant-img">'},
  lait_coco:{name:'Lait coco',emoji:'🥥',img:'<img src="farmvalley_imgs/lait_coco.svg" class="plant-img">'},chocolat:{name:'Chocolat',emoji:'🍫',img:'<img src="farmvalley_imgs/chocolat.svg" class="plant-img">'},
  sauce_tomate:{name:'Sauce tomate',emoji:'🥫',img:'<img src="farmvalley_imgs/sauce_tomate.svg" class="plant-img">'},soupe:{name:'Soupe',emoji:'🍲',img:'<img src="farmvalley_imgs/soupe.svg" class="plant-img">'},
  jus_orange:{name:'Jus orange',emoji:'🍹',img:'<img src="farmvalley_imgs/jus_orange.svg" class="plant-img">'},smoothie:{name:'Smoothie',emoji:'🥤',img:'<img src="farmvalley_imgs/smoothie.svg" class="plant-img">'},
  marmelade:{name:'Marmelade',emoji:'🏺',img:'<img src="farmvalley_imgs/marmelade.svg" class="plant-img">'},cidre:{name:'Cidre',emoji:'🍺',img:'<img src="farmvalley_imgs/cidre.svg" class="plant-img">'},
  charcuterie:{name:'Charcuterie',emoji:'🥓',img:'<img src="farmvalley_imgs/charcuterie.svg" class="plant-img">'},saucisse:{name:'Saucisse',emoji:'🌭',img:'<img src="farmvalley_imgs/saucisse.svg" class="plant-img">'},
  pizza:{name:'Pizza',emoji:'🍕',img:'<img src="farmvalley_imgs/pizza.svg" class="plant-img">'},risotto:{name:'Risotto',emoji:'🍚',img:'<img src="farmvalley_imgs/risotto.svg" class="plant-img">'},
  tarte_citrouille:{name:'Tarte citrouille',emoji:'🥧',img:'<img src="farmvalley_imgs/tarte_citrouille.svg" class="plant-img">'},
  parfum:{name:'Parfum',emoji:'🌺',img:'<img src="farmvalley_imgs/parfum.svg" class="plant-img">'},bougie:{name:'Bougie',emoji:'🕯️',img:'<img src="farmvalley_imgs/bougie.svg" class="plant-img">'},
  coussin:{name:'Coussin',emoji:'🛋️',img:'<img src="farmvalley_imgs/coussin.svg" class="plant-img">'},roti_dinde:{name:'Rôti dinde',emoji:'🍗',img:'<img src="farmvalley_imgs/roti_dinde.svg" class="plant-img">'},
  salade_composee:{name:'Salade',emoji:'🥗',img:'<img src="farmvalley_imgs/salade_composee.svg" class="plant-img">'},
  compote:{name:'Compote',emoji:'🍯',img:'<img src="farmvalley_imgs/compote.svg" class="plant-img">'},
  jus_poire:{name:'Jus poire',emoji:'🍐',img:'<img src="farmvalley_imgs/jus_poire.svg" class="plant-img">'},
  jus_cerise:{name:'Jus cerise',emoji:'🍒',img:'<img src="farmvalley_imgs/jus_cerise.svg" class="plant-img">'},
  semoule:{name:'Semoule',emoji:'🍚',img:'<img src="farmvalley_imgs/semoule.svg" class="plant-img">'},
  soupe_citrouille:{name:'Soupe citrouille',emoji:'🎃',img:'<img src="farmvalley_imgs/soupe_citrouille.svg" class="plant-img">'},
  ratatouille:{name:'Ratatouille',emoji:'🍆',img:'<img src="farmvalley_imgs/ratatouille.svg" class="plant-img">'},
  gaspacho:{name:'Gaspacho',emoji:'🥒',img:'<img src="farmvalley_imgs/gaspacho.svg" class="plant-img">'},
  soupe_brocoli:{name:'Soupe brocoli',emoji:'🥦',img:'<img src="farmvalley_imgs/soupe_brocoli.svg" class="plant-img">'},
  pesto_ail:{name:'Pesto ail',emoji:'🧄',img:'<img src="farmvalley_imgs/pesto_ail.svg" class="plant-img">'},
  pelote:{name:'Pelote',emoji:'🧶',img:'<img src="farmvalley_imgs/pelote.svg" class="plant-img">'},
  tapis:{name:'Tapis',emoji:'🧶',img:'<img src="farmvalley_imgs/tapis.svg" class="plant-img">'},
  fondue:{name:'Fondue',emoji:'🫕',img:'<img src="farmvalley_imgs/fondue.svg" class="plant-img">'},
  raclette:{name:'Raclette',emoji:'🧀',img:'<img src="farmvalley_imgs/raclette.svg" class="plant-img">'},
  brie:{name:'Brie',emoji:'🧀',img:'<img src="farmvalley_imgs/brie.svg" class="plant-img">'},
  popcorn:{name:'Pop-corn',emoji:'🍿',img:'<img src="farmvalley_imgs/popcorn.svg" class="plant-img">'},
  pain:{name:'Pain',emoji:'🍞',img:'<img src="farmvalley_imgs/pain.svg" class="plant-img">'},
  tortilla:{name:'Tortilla',emoji:'🫔',img:'<img src="farmvalley_imgs/tortilla.svg" class="plant-img">'},
  brioche:{name:'Brioche',emoji:'🍞',img:'<img src="farmvalley_imgs/brioche.svg" class="plant-img">'},
  muffin:{name:'Muffin',emoji:'🧁',img:'<img src="farmvalley_imgs/muffin.svg" class="plant-img">'},
  steak_sauce:{name:'Steak sauce',emoji:'🍖',img:'<img src="farmvalley_imgs/steak_sauce.svg" class="plant-img">'},
  jus_citron:{name:'Jus citron',emoji:'🍋',img:'<img src="farmvalley_imgs/jus_citron.svg" class="plant-img">'},
  piment_confit:{name:'Piment confit',emoji:'🌶️',img:'<img src="farmvalley_imgs/piment_confit.svg" class="plant-img">'},
  confiture_melon:{name:'Confiture melon',emoji:'🍈',img:'<img src="farmvalley_imgs/confiture_melon.svg" class="plant-img">'},
  bonbon_miel:{name:'Bonbon miel',emoji:'🍬',img:'<img src="farmvalley_imgs/bonbon_miel.svg" class="plant-img">'},
  nougat:{name:'Nougat',emoji:'🥜',img:'<img src="farmvalley_imgs/nougat.svg" class="plant-img">'},
  hydromel:{name:'Hydromel',emoji:'🍾',img:'<img src="farmvalley_imgs/hydromel.svg" class="plant-img">'},
  cocktail:{name:'Cocktail',emoji:'🍹',img:'<img src="farmvalley_imgs/cocktail.svg" class="plant-img">'},
  jus_mangue:{name:'Jus mangue',emoji:'🥭',img:'<img src="farmvalley_imgs/jus_mangue.svg" class="plant-img">'},
  milkshake_fraise:{name:'Milkshake fraise',emoji:'🍓',img:'<img src="farmvalley_imgs/milkshake_fraise.svg" class="plant-img">'},
  confiture_cerise:{name:'Confiture cerise',emoji:'🍒',img:'<img src="farmvalley_imgs/confiture_cerise.svg" class="plant-img">'},
  vinaigre:{name:'Vinaigre',emoji:'🫧',img:'<img src="farmvalley_imgs/vinaigre.svg" class="plant-img">'},
  vin_premium:{name:'Vin premium',emoji:'🥂',img:'<img src="farmvalley_imgs/vin_premium.svg" class="plant-img">'},
  sangria:{name:'Sangria',emoji:'🍷',img:'<img src="farmvalley_imgs/sangria.svg" class="plant-img">'},
  ratafia:{name:'Ratafia',emoji:'🍇',img:'<img src="farmvalley_imgs/ratafia.svg" class="plant-img">'},
  calzone:{name:'Calzone',emoji:'🫔',img:'<img src="farmvalley_imgs/calzone.svg" class="plant-img">'},
  pizza_champignon:{name:'Pizza champignon',emoji:'🍕',img:'<img src="farmvalley_imgs/pizza_champignon.svg" class="plant-img">'},
  tapenade:{name:'Tapenade',emoji:'🫧',img:'<img src="farmvalley_imgs/tapenade.svg" class="plant-img">'},
  jus_tropical:{name:'Jus tropical',emoji:'🍹',img:'<img src="farmvalley_imgs/jus_tropical.svg" class="plant-img">'},
  punch_exotique:{name:'Punch exotique',emoji:'🍸',img:'<img src="farmvalley_imgs/punch_exotique.svg" class="plant-img">'},
  sirop_piment:{name:'Sirop piment',emoji:'🌶️',img:'<img src="farmvalley_imgs/sirop_piment.svg" class="plant-img">'},
  collier_corail:{name:'Collier corail',emoji:'🪢',img:'<img src="farmvalley_imgs/collier_corail.svg" class="plant-img">'},
  huile_tortue:{name:'Huile tortue',emoji:'🐢',img:'<img src="farmvalley_imgs/huile_tortue.svg" class="plant-img">'},
  tarte_fruits:{name:'Tarte fruits',emoji:'🥧',img:'<img src="farmvalley_imgs/tarte_fruits.svg" class="plant-img">'},
  croissant:{name:'Croissant',emoji:'🥐',img:'<img src="farmvalley_imgs/croissant.svg" class="plant-img">'},
  macaron:{name:'Macaron',emoji:'🧁',img:'<img src="farmvalley_imgs/macaron.svg" class="plant-img">'},
  tarte_caramel:{name:'Tarte caramel',emoji:'🍮',img:'<img src="farmvalley_imgs/tarte_caramel.svg" class="plant-img">'},
  flan_caramel:{name:'Flan caramel',emoji:'🍮',img:'<img src="farmvalley_imgs/flan_caramel.svg" class="plant-img">'},
  potion_magique:{name:'Potion magique',emoji:'🧪',img:'<img src="farmvalley_imgs/potion_magique.svg" class="plant-img">'},
  manteau_plumes:{name:'Manteau plumes',emoji:'🧥',img:'<img src="farmvalley_imgs/manteau_plumes.svg" class="plant-img">'},
  bijou_corail:{name:'Bijou corail',emoji:'💎',img:'<img src="farmvalley_imgs/bijou_corail.svg" class="plant-img">'},
  parfum_lavande:{name:'Parfum lavande',emoji:'💜',img:'<img src="farmvalley_imgs/parfum_lavande.svg" class="plant-img">'},
  bougie_romarin:{name:'Bougie romarin',emoji:'🕯️',img:'<img src="farmvalley_imgs/bougie_romarin.svg" class="plant-img">'},
  sachet_herbes:{name:'Sachet herbes',emoji:'🌿',img:'<img src="farmvalley_imgs/sachet_herbes.svg" class="plant-img">'},
  truffes:{name:'Truffes',emoji:'🟤',img:'<img src="farmvalley_imgs/truffes.svg" class="plant-img">'},
  fontaine_choco:{name:'Fontaine choco',emoji:'🫕',img:'<img src="farmvalley_imgs/fontaine_choco.svg" class="plant-img">'},
  brownie:{name:'Brownie',emoji:'🍫',img:'<img src="farmvalley_imgs/brownie.svg" class="plant-img">'},
  mousse_choco:{name:'Mousse choco',emoji:'🫕',img:'<img src="farmvalley_imgs/mousse_choco.svg" class="plant-img">'},
  chocolat_caramel:{name:'Chocolat caramel',emoji:'🍬',img:'<img src="farmvalley_imgs/chocolat_caramel.svg" class="plant-img">'},
  soupe_poisson:{name:'Soupe de poisson',emoji:'🍲',img:'<img src="farmvalley_imgs/soupe_poisson.svg" class="plant-img">'},
  fish_chips:{name:'Fish & chips',emoji:'🍟',img:'<img src="farmvalley_imgs/fish_chips.svg" class="plant-img">'},
  bouillabaisse:{name:'Bouillabaisse',emoji:'🥘',img:'<img src="farmvalley_imgs/bouillabaisse.svg" class="plant-img">'},
  carpaccio_marin:{name:'Carpaccio marin',emoji:'🥡',img:'<img src="farmvalley_imgs/carpaccio_marin.svg" class="plant-img">'},
  brochettes:{name:'Brochettes',emoji:'🍢',img:'<img src="farmvalley_imgs/brochettes.svg" class="plant-img">'},
  festin_dinde:{name:'Festin dinde',emoji:'🦃',img:'<img src="farmvalley_imgs/festin_dinde.svg" class="plant-img">'},
  gigot_ail:{name:'Gigot ail',emoji:'🍖',img:'<img src="farmvalley_imgs/gigot_ail.svg" class="plant-img">'},
  menu_gastro:{name:'Menu gastro',emoji:'🍽️',img:'<img src="farmvalley_imgs/menu_gastro.svg" class="plant-img">'},
  festin_royal:{name:'Festin royal',emoji:'👑',img:'<img src="farmvalley_imgs/festin_royal.svg" class="plant-img">'},
  banquet:{name:'Banquet',emoji:'🎉',img:'<img src="farmvalley_imgs/banquet.svg" class="plant-img">'},
  plateau_mer:{name:'Plateau mer',emoji:'🥡',img:'<img src="farmvalley_imgs/plateau_mer.svg" class="plant-img">'},
  thon_huile:{name:'Thon huile',emoji:'🐟',img:'<img src="farmvalley_imgs/thon_huile.svg" class="plant-img">'},
  tartare_marin:{name:'Tartare marin',emoji:'🥡',img:'<img src="farmvalley_imgs/tartare_marin.svg" class="plant-img">'},
  festin_steak:{name:'Festin steak',emoji:'🥩',img:'<img src="farmvalley_imgs/festin_steak.svg" class="plant-img">'},
  plat_magique:{name:'Plat magique',emoji:'✨',img:'<img src="farmvalley_imgs/plat_magique.svg" class="plant-img">'},
  cape_prestige:{name:'Cape prestige',emoji:'🧥',img:'<img src="farmvalley_imgs/cape_prestige.svg" class="plant-img">'},
  buffet_palace:{name:'Buffet palace',emoji:'🎆',img:'<img src="farmvalley_imgs/buffet_palace.svg" class="plant-img">'},
  gala_ultime:{name:'Gala ultime',emoji:'🏆',img:'<img src="farmvalley_imgs/gala_ultime.svg" class="plant-img">'},
  banquet_ultime:{name:'Banquet ultime',emoji:'🌟',img:'<img src="farmvalley_imgs/banquet_ultime.svg" class="plant-img">'},
  festin_marin_royal:{name:'Festin marin royal',emoji:'👑',img:'<img src="farmvalley_imgs/festin_marin_royal.svg" class="plant-img">'},
  salade_fraiche:{name:'Salade fra\u00eeche',emoji:'🥬',img:'<img src="farmvalley_imgs/salade_fraiche.svg" class="plant-img">'},
  meli_melo:{name:'M\u00e9li-m\u00e9lo',emoji:'🫕',img:'<img src="farmvalley_imgs/meli_melo.svg" class="plant-img">'},
  puree:{name:'Pur\u00e9e',emoji:'🥔',img:'<img src="farmvalley_imgs/puree.svg" class="plant-img">'},
  echarpe:{name:'\u00c9charpe',emoji:'🧣',img:'<img src="farmvalley_imgs/echarpe.svg" class="plant-img">'},
  chapeau_plume:{name:'Chapeau plum\u00e9',emoji:'🧢',img:'<img src="farmvalley_imgs/chapeau_plume.svg" class="plant-img">'},
  fromage_chevre:{name:'Fromage ch\u00e8vre',emoji:'🧀',img:'<img src="farmvalley_imgs/fromage_chevre.svg" class="plant-img">'},
  barbe_a_papa:{name:'Barbe \u00e0 papa',emoji:'🍭',img:'<img src="farmvalley_imgs/barbe_a_papa.svg" class="plant-img">'},
  gateau:{name:'G\u00e2teau',emoji:'🎂',img:'<img src="farmvalley_imgs/gateau.svg" class="plant-img">'},
  crepes:{name:'Cr\u00eapes',emoji:'🥞',img:'<img src="farmvalley_imgs/crepes.svg" class="plant-img">'},
  pate:{name:'P\u00e2t\u00e9',emoji:'🥫',img:'<img src="farmvalley_imgs/pate.svg" class="plant-img">'},
  steak_grille:{name:'Steak grill\u00e9',emoji:'🥩',img:'<img src="farmvalley_imgs/steak_grille.svg" class="plant-img">'},
  gelee:{name:'Gel\u00e9e',emoji:'🍏',img:'<img src="farmvalley_imgs/gelee.svg" class="plant-img">'},
  pain_epices:{name:'Pain d\u2019\u00e9pices',emoji:'🍞',img:'<img src="farmvalley_imgs/pain_epices.svg" class="plant-img">'},
  smoothie_peche:{name:'Smoothie p\u00eache',emoji:'🍑',img:'<img src="farmvalley_imgs/smoothie_peche.svg" class="plant-img">'},
  jus_pasteque:{name:'Jus past\u00e8que',emoji:'🍉',img:'<img src="farmvalley_imgs/jus_pasteque.svg" class="plant-img">'},
  pizza_legumes:{name:'Pizza l\u00e9gumes',emoji:'🍕',img:'<img src="farmvalley_imgs/pizza_legumes.svg" class="plant-img">'},
  limonade_pasteque:{name:'Limonade past\u00e8que',emoji:'🍉',img:'<img src="farmvalley_imgs/limonade_pasteque.svg" class="plant-img">'},
  aquarium_deco:{name:'Aquarium d\u00e9co',emoji:'🐠',img:'<img src="farmvalley_imgs/aquarium_deco.svg" class="plant-img">'},
  plumeau_enchante:{name:'Plumeau enchant\u00e9',emoji:'🪶',img:'<img src="farmvalley_imgs/plumeau_enchante.svg" class="plant-img">'},
  pralines:{name:'Pralin\u00e9s',emoji:'🍬',img:'<img src="farmvalley_imgs/pralines.svg" class="plant-img">'},
  poisson_grille:{name:'Poisson grill\u00e9',emoji:'🍽️',img:'<img src="farmvalley_imgs/poisson_grille.svg" class="plant-img">'},
  poulet_roti:{name:'Poulet r\u00f4ti',emoji:'🍗',img:'<img src="farmvalley_imgs/poulet_roti.svg" class="plant-img">'},
  cotelettes:{name:'C\u00f4telettes',emoji:'🥩',img:'<img src="farmvalley_imgs/cotelettes.svg" class="plant-img">'},
  entrecote_royale:{name:'Entrec\u00f4te royale',emoji:'🥩',img:'<img src="farmvalley_imgs/entrecote_royale.svg" class="plant-img">'},
  omelette_geante:{name:'Omelette g\u00e9ante',emoji:'🍳',img:'<img src="farmvalley_imgs/omelette_geante.svg" class="plant-img">'},
  diner_royal:{name:'D\u00eener royal',emoji:'👑',img:'<img src="farmvalley_imgs/diner_royal.svg" class="plant-img">'},
  pommade:{name:'Pommade',emoji:'🩹',img:'<img src="farmvalley_imgs/pommade.svg" class="plant-img">'},baume_levres:{name:'Baume l\u00e8vres',emoji:'💋',img:'<img src="farmvalley_imgs/baume_levres.svg" class="plant-img">'},creme_hydratante:{name:'Cr\u00e8me hydrat.',emoji:'🧴',img:'<img src="farmvalley_imgs/creme_hydratante.svg" class="plant-img">'},
  lotion_apaisante:{name:'Lotion apais.',emoji:'💧',img:'<img src="farmvalley_imgs/lotion_apaisante.svg" class="plant-img">'},masque_beaute:{name:'Masque beaut\u00e9',emoji:'🧖',img:'<img src="farmvalley_imgs/masque_beaute.svg" class="plant-img">'},shampoing:{name:'Shampoing',emoji:'🧴',img:'<img src="farmvalley_imgs/shampoing.svg" class="plant-img">'},
  gel_douche:{name:'Gel douche',emoji:'🚿',img:'<img src="farmvalley_imgs/gel_douche.svg" class="plant-img">'},savon:{name:'Savon',emoji:'🧼',img:'<img src="farmvalley_imgs/savon.svg" class="plant-img">'},huile_lavande:{name:'Huile lavande',emoji:'💜',img:'<img src="farmvalley_imgs/huile_lavande.svg" class="plant-img">'},
  huile_menthe:{name:'Huile menthe',emoji:'🌿',img:'<img src="farmvalley_imgs/huile_menthe.svg" class="plant-img">'},parfum_naturel:{name:'Parfum naturel',emoji:'🌸',img:'<img src="farmvalley_imgs/parfum_naturel.svg" class="plant-img">'},serum_visage:{name:'S\u00e9rum visage',emoji:'✨',img:'<img src="farmvalley_imgs/serum_visage.svg" class="plant-img">'},
  tisane_relaxante:{name:'Tisane relax.',emoji:'☕',img:'<img src="farmvalley_imgs/tisane_relaxante.svg" class="plant-img">'},tisane_digestive:{name:'Tisane digest.',emoji:'🍵',img:'<img src="farmvalley_imgs/tisane_digestive.svg" class="plant-img">'},
  sirop_medicinal:{name:'Sirop m\u00e9dicinal',emoji:'🍯',img:'<img src="farmvalley_imgs/sirop_medicinal.svg" class="plant-img">'},vinaigre_aromatique:{name:'Vinaigre arom.',emoji:'🫗',img:'<img src="farmvalley_imgs/vinaigre_aromatique.svg" class="plant-img">'},
  pesto_basilic:{name:'Pesto basilic',emoji:'🌿',img:'<img src="farmvalley_imgs/pesto_basilic.svg" class="plant-img">'},huile_aromatisee:{name:'Huile aromat.',emoji:'🫒',img:'<img src="farmvalley_imgs/huile_aromatisee.svg" class="plant-img">'},
  sel_herbes:{name:'Sel aux herbes',emoji:'🧂',img:'<img src="farmvalley_imgs/sel_herbes.svg" class="plant-img">'},sirop_citronnelle:{name:'Sirop citronn.',emoji:'🍋',img:'<img src="farmvalley_imgs/sirop_citronnelle.svg" class="plant-img">'},
  bougie_aromatique:{name:'Bougie aromat.',emoji:'🕯️',img:'<img src="farmvalley_imgs/bougie_aromatique.svg" class="plant-img">'},encens:{name:'Encens',emoji:'🌫️',img:'<img src="farmvalley_imgs/encens.svg" class="plant-img">'},
  sachet_parfume:{name:'Sachet parfum\u00e9',emoji:'🌸',img:'<img src="farmvalley_imgs/sachet_parfume.svg" class="plant-img">'},spray_maison:{name:'Spray maison',emoji:'💨',img:'<img src="farmvalley_imgs/spray_maison.svg" class="plant-img">'},
  yaourt:{name:'Yaourt',emoji:'🥛',img:'<img src="farmvalley_imgs/yaourt.svg" class="plant-img">'},glace:{name:'Glace',emoji:'🍨',img:'<img src="farmvalley_imgs/glace.svg" class="plant-img">'},milkshake_abricot:{name:'Milkshake abricot',emoji:'🥤',img:'<img src="farmvalley_imgs/milkshake_abricot.svg" class="plant-img">'},
  fromage_blanc:{name:'Fromage blanc',emoji:'🧀',img:'<img src="farmvalley_imgs/fromage_blanc.svg" class="plant-img">'},jus_kiwi:{name:'Jus kiwi',emoji:'🥝',img:'<img src="farmvalley_imgs/jus_kiwi.svg" class="plant-img">'},
  smoothie_papaye:{name:'Smoothie papaye',emoji:'🍹',img:'<img src="farmvalley_imgs/smoothie_papaye.svg" class="plant-img">'},jus_grenade:{name:'Jus grenade',emoji:'🍇',img:'<img src="farmvalley_imgs/jus_grenade.svg" class="plant-img">'},
  tarte_abricot:{name:'Tarte abricot',emoji:'🍑',img:'<img src="farmvalley_imgs/tarte_abricot.svg" class="plant-img">'},gateau_noix:{name:'G\u00e2teau noix',emoji:'🎂',img:'<img src="farmvalley_imgs/gateau_noix.svg" class="plant-img">'},
  confiture_abricot:{name:'Conf. abricot',emoji:'🍑',img:'<img src="farmvalley_imgs/confiture_abricot.svg" class="plant-img">'},sirop_kiwi:{name:'Sirop kiwi',emoji:'🥝',img:'<img src="farmvalley_imgs/sirop_kiwi.svg" class="plant-img">'},
  tapenade_figue:{name:'Tapenade figue',emoji:'🫒',img:'<img src="farmvalley_imgs/tapenade_figue.svg" class="plant-img">'},guacamole:{name:'Guacamole',emoji:'🥑',img:'<img src="farmvalley_imgs/guacamole.svg" class="plant-img">'},
  compote_prune:{name:'Compote prune',emoji:'🫐',img:'<img src="farmvalley_imgs/compote_prune.svg" class="plant-img">'},confiture_litchi:{name:'Conf. litchi',emoji:'🍇',img:'<img src="farmvalley_imgs/confiture_litchi.svg" class="plant-img">'},
  creme_chataigne:{name:'Cr\u00e8me ch\u00e2taigne',emoji:'🌰',img:'<img src="farmvalley_imgs/creme_chataigne.svg" class="plant-img">'},pate_amande:{name:'P\u00e2te amande',emoji:'🌰',img:'<img src="farmvalley_imgs/pate_amande.svg" class="plant-img">'}
};
var RES_SELL={bois:20,lait:50,ble:30,mais:35,oeuf:60,laine:70,
  pomme:40,fraise:55,lait_chevre:80,citron:50,miel:100,raisin:90,noix_coco:120,olive:110,
  tomate:25,carotte:15,oignon:35,patate:30,champignon:80,citrouille:120,cerise:100,fleur:150,
  poire:45,orange:50,banane:55,peche:60,mangue:80,
  viande_porc:200,viande_dinde:250,plume:180,fourrure:160,
  steak:400,plume_blanche:600,corail:1500,plume_rose:800,corne_magique:3000,plume_verte:900,carapace:1200,poisson:300,
  oeuf_geant:500,plume_luxe:700,pelisse:8000,bois_cerf:12000,plume_irisee:18000,cendre_magique:28000,ecaille_dragon:50000,radis:10,epinards:18,petits_pois:22,lavande:120,menthe:90,romarin:130,
  basilic:15,persil:20,thym:35,camomille:55,sauge:75,origan:95,coriandre:120,citronnelle:180,verveine:250,melisse:320,
  abricot:100,prune:130,figue:160,grenade:200,avocat:250,kiwi:300,papaye:350,noix:380,chataigne:420,litchi:460,caramel:400,
  salade:20,poivron:25,concombre:18,aubergine:30,piment:40,brocoli:55,melon:65,pasteque:75,ail:90,
  beurre:200,creme:300,farine_ble:120,farine_mais:130,sucre:180,fromage:350,jus_pomme:150,confiture:500,
  vin:800,huile_olive:1000,lait_coco:900,chocolat:3000,
  sauce_tomate:250,soupe:350,jus_orange:200,smoothie:600,marmelade:450,cidre:700,
  charcuterie:800,saucisse:500,pizza:2500,risotto:2000,tarte_citrouille:1500,
  parfum:5000,bougie:2500,coussin:1200,roti_dinde:3500,salade_composee:400,
  compote:250,jus_poire:400,jus_cerise:800,semoule:200,soupe_citrouille:900,ratatouille:1200,gaspacho:900,soupe_brocoli:1500,pesto_ail:2000,pelote:600,tapis:3500,fondue:3000,raclette:2500,brie:1800,popcorn:700,pain:1500,tortilla:1800,brioche:3500,muffin:2000,steak_sauce:3500,jus_citron:800,piment_confit:1500,confiture_melon:1800,bonbon_miel:2000,nougat:4000,hydromel:3000,cocktail:1200,jus_mangue:700,milkshake_fraise:1500,confiture_cerise:1200,vinaigre:700,vin_premium:5500,sangria:3500,ratafia:4000,calzone:3200,pizza_champignon:3000,tapenade:3500,jus_tropical:1200,punch_exotique:2500,sirop_piment:2000,collier_corail:9000,huile_tortue:7000,tarte_fruits:5500,croissant:4500,macaron:7500,tarte_caramel:6000,flan_caramel:5000,potion_magique:15000,manteau_plumes:6000,bijou_corail:5000,parfum_lavande:7000,bougie_romarin:4000,sachet_herbes:5500,truffes:13000,fontaine_choco:20000,brownie:8000,mousse_choco:10000,chocolat_caramel:12000,soupe_poisson:5000,fish_chips:4000,bouillabaisse:7000,carpaccio_marin:6000,brochettes:6500,festin_dinde:18000,gigot_ail:12000,menu_gastro:15000,festin_royal:28000,banquet:45000,plateau_mer:18000,thon_huile:15000,tartare_marin:22000,festin_steak:25000,plat_magique:35000,cape_prestige:30000,buffet_palace:80000,gala_ultime:150000,banquet_ultime:120000,festin_marin_royal:100000,
  salade_fraiche:600,meli_melo:800,puree:500,echarpe:1800,chapeau_plume:1500,fromage_chevre:800,barbe_a_papa:600,gateau:3000,crepes:1000,pate:3000,steak_grille:2500,gelee:900,pain_epices:2500,smoothie_peche:1500,jus_pasteque:700,pizza_legumes:3500,limonade_pasteque:1800,aquarium_deco:12000,plumeau_enchante:8000,pralines:9000,poisson_grille:3000,poulet_roti:8000,cotelettes:9000,entrecote_royale:20000,omelette_geante:20000,diner_royal:60000,
  pommade:1500,baume_levres:1400,creme_hydratante:2500,lotion_apaisante:1800,masque_beaute:2200,shampoing:2000,gel_douche:2800,savon:1600,huile_lavande:3000,huile_menthe:2800,parfum_naturel:4000,serum_visage:3500,
  tisane_relaxante:2000,tisane_digestive:1800,sirop_medicinal:2200,vinaigre_aromatique:1500,pesto_basilic:2500,huile_aromatisee:2000,sel_herbes:1800,sirop_citronnelle:2200,
  bougie_aromatique:2500,encens:2800,sachet_parfume:2200,spray_maison:1800,
  yaourt:350,glace:800,milkshake_abricot:500,fromage_blanc:450,jus_kiwi:600,smoothie_papaye:1200,jus_grenade:800,
  tarte_abricot:4500,gateau_noix:5500,confiture_abricot:1200,sirop_kiwi:1000,tapenade_figue:1500,guacamole:1800,compote_prune:1100,confiture_litchi:1500,creme_chataigne:1600,pate_amande:2000};
var HARVEST_RES={
  'Bl\u00e9':'ble','Ma\u00efs':'mais','Poule':'oeuf','Vache':'lait','Mouton':'laine',
  'Fraise':'fraise','Pommier':'pomme','Citronnier':'citron','Vigne':'raisin',
  'Cocotier':'noix_coco','Olivier':'olive','Ch\u00e8vre':'lait_chevre','Abeille':'miel',
  'Tomate':'tomate','Carotte':'carotte','Oignon':'oignon','P.de terre':'patate',
  'Champignon':'champignon','Citrouille':'citrouille','Cerise':'cerise','Fleur dor\u00e9e':'fleur',
  'Poirier':'poire','Oranger':'orange','Bananier':'banane','P\u00eacher':'peche','Manguier':'mangue',
  'Cochon':'viande_porc','Dinde':'viande_dinde','Paon':'plume','Lapin':'fourrure',
  'Salade':'salade','Poivron':'poivron','Concombre':'concombre','Aubergine':'aubergine',
  'Piment':'piment','Brocoli':'brocoli','Melon':'melon','Pastèque':'pasteque','Ail':'ail',
  'Cheval':'steak','Cygne':'plume_blanche','Dauphin':'corail','Flamant':'plume_rose',
  'Hibou':'plume','Licorne':'corne_magique','Perroquet':'plume_verte','Tortue':'carapace',
  'Saumon':'poisson','Autruche':'oeuf_geant','Pintade':'plume_luxe',
  'Renard':'pelisse','Cerf':'bois_cerf','Paon blanc':'plume_irisee','Ph\u00e9nix':'cendre_magique','Dragon':'ecaille_dragon',
  'Radis':'radis','\u00c9pinards':'epinards','Petits pois':'petits_pois',
  'Lavande':'lavande','Menthe':'menthe','Romarin':'romarin',
  'Basilic':'basilic','Persil':'persil','Thym':'thym','Camomille':'camomille','Sauge':'sauge',
  'Origan':'origan','Coriandre':'coriandre','Citronnelle':'citronnelle','Verveine':'verveine','M\u00e9lisse':'melisse',
  'Abricotier':'abricot','Prunier':'prune','Figuier':'figue','Grenadier':'grenade','Avocatier':'avocat',
  'Kiwi':'kiwi','Papayer':'papaye','Noyer':'noix','Ch\u00e2taignier':'chataigne','Litchi':'litchi'};

// ===== BUILDINGS =====
var BUILDINGS=[
  // ─── Tier 1 : D\u00e9buts (lv3-5) ───
  {id:'pressoir',name:'Pressoir',emoji:'\ud83c\udf4e',cost:2000,reqLevel:3,recipes:[
    {name:'Jus pomme',emoji:'\ud83e\uddc3',inputs:{pomme:2},output:'jus_pomme',time:15,sell:150,xp:20},
    {name:'Compote',emoji:'\ud83c\udf6f',inputs:{pomme:3},output:'compote',time:20,sell:250,xp:25},
    {name:'Jus poire',emoji:'\ud83c\udf50',inputs:{poire:2,sucre:1},output:'jus_poire',time:18,sell:400,xp:35},
    {name:'Jus cerise',emoji:'\ud83c\udf52',inputs:{cerise:2},output:'jus_cerise',time:15,sell:800,xp:60},
    {name:'Jus kiwi',emoji:'\ud83e\udd5d',inputs:{kiwi:2},output:'jus_kiwi',time:15,sell:600,xp:50}]},
  {id:'potager',name:'Potager',emoji:'\ud83e\udd57',cost:2500,reqLevel:4,recipes:[
    {name:'Soupe',emoji:'\ud83c\udf72',inputs:{patate:2,carotte:2,oignon:1},output:'soupe',time:20,sell:350,xp:30},
    {name:'Salade',emoji:'\ud83e\udd57',inputs:{tomate:2,oeuf:1},output:'salade_composee',time:12,sell:400,xp:20},
    {name:'Salade fra\u00eeche',emoji:'\ud83e\udd6c',inputs:{salade:2,concombre:1,tomate:1},output:'salade_fraiche',time:15,sell:600,xp:40},
    {name:'M\u00e9li-m\u00e9lo',emoji:'\ud83e\uded1',inputs:{poivron:2,melon:1,salade:1},output:'meli_melo',time:18,sell:800,xp:55}]},
  {id:'moulin',name:'Moulin',emoji:'\ud83c\udfed',cost:3000,reqLevel:5,recipes:[
    {name:'Farine bl\u00e9',emoji:'\ud83e\uded3',inputs:{ble:2},output:'farine_ble',time:20,sell:120,xp:30},
    {name:'Farine ma\u00efs',emoji:'\ud83e\uded3',inputs:{mais:2},output:'farine_mais',time:25,sell:130,xp:35},
    {name:'Semoule',emoji:'\ud83c\udf5a',inputs:{mais:3},output:'semoule',time:30,sell:200,xp:40}]},
  // ─── Tier 2 : Transformation (lv6-10) ───
  {id:'cuisinette',name:'Cuisinette',emoji:'\ud83c\udf73',cost:3500,reqLevel:6,recipes:[
    {name:'Sauce tomate',emoji:'\ud83e\udd6b',inputs:{tomate:3,oignon:1},output:'sauce_tomate',time:18,sell:250,xp:35},
    {name:'Pur\u00e9e',emoji:'\ud83e\udd54',inputs:{patate:3,beurre:1},output:'puree',time:15,sell:500,xp:40},
    {name:'Soupe citrouille',emoji:'\ud83c\udf83',inputs:{citrouille:2,creme:1},output:'soupe_citrouille',time:25,sell:900,xp:55},
    {name:'Ratatouille',emoji:'\ud83c\udf46',inputs:{aubergine:2,poivron:2,tomate:2},output:'ratatouille',time:22,sell:1200,xp:80},
    {name:'Gaspacho',emoji:'\ud83e\udd52',inputs:{concombre:3,tomate:2,ail:1},output:'gaspacho',time:18,sell:900,xp:65},
    {name:'Soupe brocoli',emoji:'\ud83e\udd66',inputs:{brocoli:2,ail:1,oignon:1},output:'soupe_brocoli',time:20,sell:1500,xp:100},
    {name:'Pesto ail',emoji:'\ud83e\uddc4',inputs:{ail:3,huile_olive:1},output:'pesto_ail',time:15,sell:2000,xp:120}]},
  {id:'lainerie',name:'Mag. laine',emoji:'\ud83e\uddf6',cost:4000,reqLevel:8,recipes:[
    {name:'Pelote',emoji:'\ud83e\uddf6',inputs:{laine:2},output:'pelote',time:30,sell:600,xp:40},
    {name:'\u00c9charpe',emoji:'\ud83e\udde3',inputs:{laine:5},output:'echarpe',time:60,sell:1800,xp:120},
    {name:'Tapis',emoji:'\ud83e\uddf6',inputs:{laine:8},output:'tapis',time:80,sell:3500,xp:200},
    {name:'Chapeau plum\u00e9',emoji:'\ud83e\udde2',inputs:{laine:3,plume:1},output:'chapeau_plume',time:40,sell:1500,xp:100}]},
  {id:'fromagerie',name:'Fromagerie',emoji:'\ud83e\uddc0',cost:5500,reqLevel:9,recipes:[
    {name:'Fromage ch\u00e8vre',emoji:'\ud83e\uddc0',inputs:{lait_chevre:2},output:'fromage_chevre',time:35,sell:800,xp:60},
    {name:'Fromage',emoji:'\ud83e\uddc0',inputs:{lait:3},output:'fromage',time:40,sell:350,xp:55},
    {name:'Fondue',emoji:'\ud83e\udd62',inputs:{fromage:3,lait:1},output:'fondue',time:55,sell:3000,xp:150},
    {name:'Raclette',emoji:'\ud83e\uddc0',inputs:{fromage:2,patate:2},output:'raclette',time:40,sell:2500,xp:130},
    {name:'Brie',emoji:'\ud83e\uddc0',inputs:{lait:4,champignon:1},output:'brie',time:50,sell:1800,xp:100}]},
  {id:'laiterie',name:'Laiterie',emoji:'\ud83e\udd5b',cost:5000,reqLevel:10,recipes:[
    {name:'Beurre',emoji:'\ud83e\uddc8',inputs:{lait:2},output:'beurre',time:30,sell:200,xp:50},
    {name:'Cr\u00e8me',emoji:'\ud83c\udf66',inputs:{lait:3},output:'creme',time:45,sell:300,xp:80},
    {name:'Yaourt fruit\u00e9',emoji:'\ud83e\udd5b',inputs:{lait:2,fraise:1},output:'yaourt',time:25,sell:350,xp:60},
    {name:'Glace artisanale',emoji:'\ud83c\udf68',inputs:{creme:1,sucre:1,banane:1},output:'glace',time:40,sell:800,xp:90},
    {name:'Milkshake abricot',emoji:'\ud83e\udd64',inputs:{lait:2,abricot:1},output:'milkshake_abricot',time:20,sell:500,xp:65},
    {name:'Fromage blanc',emoji:'\ud83e\uddc0',inputs:{lait:3,creme:1},output:'fromage_blanc',time:35,sell:450,xp:70}]},
  // ─── Tier 3 : Production (lv11-14) ───
  {id:'sucrerie',name:'Sucrerie',emoji:'\ud83c\udf6c',cost:7000,reqLevel:11,recipes:[
    {name:'Sucre',emoji:'\ud83c\udf5a',inputs:{mais:3},output:'sucre',time:25,sell:180,xp:45},
    {name:'Pop-corn',emoji:'\ud83c\udf7f',inputs:{mais:2,beurre:1},output:'popcorn',time:20,sell:700,xp:55},
    {name:'Caramel',emoji:'\ud83c\udf6e',inputs:{sucre:3,beurre:1},output:'caramel',time:25,sell:400,xp:60},
    {name:'Barbe \u00e0 papa',emoji:'\ud83c\udf6d',inputs:{sucre:2},output:'barbe_a_papa',time:15,sell:600,xp:45}]},
  {id:'boulangerie',name:'Boulangerie',emoji:'\ud83e\udd56',cost:8000,reqLevel:12,recipes:[
    {name:'Pain',emoji:'\ud83c\udf5e',inputs:{farine_ble:2,beurre:1},output:'pain',time:40,sell:1500,xp:100},
    {name:'G\u00e2teau',emoji:'\ud83c\udf82',inputs:{oeuf:3,farine_ble:2,beurre:2},output:'gateau',time:60,sell:3000,xp:200},
    {name:'Cr\u00eapes',emoji:'\ud83e\udd5e',inputs:{oeuf:2,farine_ble:1},output:'crepes',time:25,sell:1000,xp:60},
    {name:'Tortilla',emoji:'\ud83e\uded4',inputs:{farine_mais:2,fromage:1},output:'tortilla',time:35,sell:1800,xp:90},
    {name:'Brioche',emoji:'\ud83c\udf5e',inputs:{farine_ble:2,beurre:3,oeuf:2},output:'brioche',time:50,sell:3500,xp:220},
    {name:'Muffin',emoji:'\ud83e\uddc1',inputs:{farine_ble:1,beurre:1,confiture:1},output:'muffin',time:30,sell:2000,xp:120}]},
  {id:'boucherie',name:'Boucherie',emoji:'\ud83e\udd69',cost:10000,reqLevel:13,recipes:[
    {name:'Charcuterie',emoji:'\ud83e\udd69',inputs:{viande_porc:2},output:'charcuterie',time:35,sell:800,xp:70},
    {name:'Saucisse',emoji:'\ud83c\udf2d',inputs:{viande_porc:2,oignon:1},output:'saucisse',time:30,sell:500,xp:55},
    {name:'R\u00f4ti dinde',emoji:'\ud83c\udf57',inputs:{viande_dinde:2,patate:2},output:'roti_dinde',time:45,sell:3500,xp:130},
    {name:'P\u00e2t\u00e9',emoji:'\ud83e\udd6b',inputs:{viande_porc:3,oeuf:2,oignon:1},output:'pate',time:50,sell:3000,xp:150},
    {name:'Steak grill\u00e9',emoji:'\ud83e\udd69',inputs:{steak:2,champignon:1},output:'steak_grille',time:35,sell:2500,xp:140},
    {name:'Steak sauce',emoji:'\ud83c\udf56',inputs:{steak:2,sauce_tomate:1,oignon:1},output:'steak_sauce',time:40,sell:3500,xp:200}]},
  {id:'conserverie',name:'Conserverie',emoji:'\ud83e\udd6b',cost:12000,reqLevel:14,recipes:[
    {name:'Confiture',emoji:'\ud83c\udf53',inputs:{fraise:3,sucre:1},output:'confiture',time:30,sell:500,xp:70},
    {name:'Jus citron',emoji:'\ud83c\udf4b',inputs:{citron:2,sucre:1},output:'jus_citron',time:25,sell:800,xp:65},
    {name:'Gel\u00e9e',emoji:'\ud83c\udf4f',inputs:{jus_pomme:2,sucre:1},output:'gelee',time:30,sell:900,xp:75},
    {name:'Marmelade',emoji:'\ud83c\udf4a',inputs:{orange:3,sucre:1},output:'marmelade',time:30,sell:450,xp:65},
    {name:'Piment confit',emoji:'\ud83c\udf36\ufe0f',inputs:{piment:3,sucre:1},output:'piment_confit',time:25,sell:1500,xp:100},
    {name:'Confiture melon',emoji:'\ud83c\udf48',inputs:{melon:3,sucre:2},output:'confiture_melon',time:30,sell:1800,xp:110}]},
  // ─── Tier 4 : Sp\u00e9cialit\u00e9s (lv15-20) ───
  {id:'miellerie',name:'Miellerie',emoji:'\ud83c\udf6f',cost:15000,reqLevel:15,recipes:[
    {name:'Bonbon miel',emoji:'\ud83c\udf6c',inputs:{miel:2,sucre:2},output:'bonbon_miel',time:30,sell:2000,xp:100},
    {name:'Nougat',emoji:'\ud83e\udd5c',inputs:{miel:3,oeuf:2,sucre:1},output:'nougat',time:50,sell:4000,xp:180},
    {name:'Pain d\u2019\u00e9pices',emoji:'\ud83c\udf5e',inputs:{miel:2,farine_ble:2},output:'pain_epices',time:40,sell:2500,xp:140},
    {name:'Hydromel',emoji:'\ud83c\udf7e',inputs:{miel:3,citron:1},output:'hydromel',time:45,sell:3000,xp:160}]},
  {id:'conserverie_fruits',name:'Conserverie fruits',emoji:'\ud83c\udf51',cost:16000,reqLevel:15,recipes:[
    {name:'Confiture abricot',emoji:'\ud83c\udf51',inputs:{abricot:3,sucre:1},output:'confiture_abricot',time:25,sell:1200,xp:80},
    {name:'Sirop kiwi',emoji:'\ud83e\udd5d',inputs:{kiwi:2,sucre:1},output:'sirop_kiwi',time:20,sell:1000,xp:70},
    {name:'Tapenade figue',emoji:'\ud83e\udeda',inputs:{figue:3,olive:1},output:'tapenade_figue',time:30,sell:1500,xp:100},
    {name:'Guacamole',emoji:'\ud83e\udd51',inputs:{avocat:3,citron:1,oignon:1},output:'guacamole',time:20,sell:1800,xp:110},
    {name:'Compote prune',emoji:'\ud83e\uded0',inputs:{prune:3,sucre:1},output:'compote_prune',time:25,sell:1100,xp:75},
    {name:'Confiture litchi',emoji:'\ud83c\udf47',inputs:{litchi:3,sucre:1},output:'confiture_litchi',time:25,sell:1500,xp:95},
    {name:'Cr\u00e8me ch\u00e2taigne',emoji:'\ud83c\udf30',inputs:{chataigne:3,sucre:1},output:'creme_chataigne',time:30,sell:1600,xp:100},
    {name:'P\u00e2te d\'amande',emoji:'\ud83c\udf30',inputs:{noix:3,sucre:2,oeuf:1},output:'pate_amande',time:35,sell:2000,xp:120}]},
  {id:'bar_jus',name:'Bar \u00e0 jus',emoji:'\ud83e\udd64',cost:18000,reqLevel:16,recipes:[
    {name:'Jus orange',emoji:'\ud83e\uddc3',inputs:{orange:3},output:'jus_orange',time:15,sell:200,xp:40},
    {name:'Smoothie',emoji:'\ud83e\udd64',inputs:{banane:2,fraise:2,mangue:1},output:'smoothie',time:25,sell:600,xp:80},
    {name:'Cocktail',emoji:'\ud83c\udf79',inputs:{jus_pomme:1,jus_orange:1,citron:1},output:'cocktail',time:20,sell:1200,xp:100},
    {name:'Jus mangue',emoji:'\ud83e\udd6d',inputs:{mangue:2},output:'jus_mangue',time:15,sell:700,xp:60},
    {name:'Milkshake fraise',emoji:'\ud83c\udf53',inputs:{lait:2,fraise:2},output:'milkshake_fraise',time:20,sell:1500,xp:100},
    {name:'Smoothie papaye',emoji:'\ud83c\udf79',inputs:{papaye:2,banane:1},output:'smoothie_papaye',time:20,sell:1200,xp:90},
    {name:'Jus grenade',emoji:'\ud83c\udf47',inputs:{grenade:2},output:'jus_grenade',time:15,sell:800,xp:70}]},
  {id:'cidrerie',name:'Cidrerie',emoji:'\ud83c\udf7a',cost:20000,reqLevel:17,recipes:[
    {name:'Cidre',emoji:'\ud83c\udf7a',inputs:{pomme:4,sucre:1},output:'cidre',time:40,sell:700,xp:90},
    {name:'Confiture cerise',emoji:'\ud83c\udf52',inputs:{cerise:3,sucre:1},output:'confiture_cerise',time:30,sell:1200,xp:85},
    {name:'Smoothie p\u00eache',emoji:'\ud83c\udf51',inputs:{peche:3,banane:1,lait:1},output:'smoothie_peche',time:25,sell:1500,xp:95},
    {name:'Jus past\u00e8que',emoji:'\ud83c\udf49',inputs:{pasteque:3},output:'jus_pasteque',time:20,sell:700,xp:60}]},
  {id:'cave',name:'Cave \u00e0 vin',emoji:'\ud83c\udf77',cost:22000,reqLevel:18,recipes:[
    {name:'Vin',emoji:'\ud83c\udf77',inputs:{raisin:3},output:'vin',time:50,sell:800,xp:110},
    {name:'Vinaigre',emoji:'\ud83e\udec7',inputs:{raisin:2,pomme:1},output:'vinaigre',time:35,sell:700,xp:80},
    {name:'Vin premium',emoji:'\ud83e\udd42',inputs:{raisin:5,miel:1},output:'vin_premium',time:80,sell:5500,xp:280},
    {name:'Sangria',emoji:'\ud83c\udf77',inputs:{vin:1,orange:2,citron:1},output:'sangria',time:30,sell:3500,xp:180},
    {name:'Ratafia',emoji:'\ud83c\udf47',inputs:{raisin:3,cerise:2},output:'ratafia',time:40,sell:4000,xp:200}]},
  {id:'pizzeria',name:'Pizzeria',emoji:'\ud83c\udf55',cost:28000,reqLevel:19,recipes:[
    {name:'Pizza',emoji:'\ud83c\udf55',inputs:{farine_ble:2,sauce_tomate:1,fromage:2},output:'pizza',time:30,sell:2500,xp:120},
    {name:'Calzone',emoji:'\ud83e\uded4',inputs:{farine_ble:2,sauce_tomate:1,charcuterie:1,fromage:1},output:'calzone',time:35,sell:3200,xp:150},
    {name:'Risotto',emoji:'\ud83c\udf5a',inputs:{mais:3,champignon:2,fromage:1,beurre:1},output:'risotto',time:40,sell:2000,xp:110},
    {name:'Pizza l\u00e9gumes',emoji:'\ud83c\udf55',inputs:{farine_ble:2,sauce_tomate:1,poivron:2,aubergine:1},output:'pizza_legumes',time:35,sell:3500,xp:170},
    {name:'Pizza champignon',emoji:'\ud83c\udf55',inputs:{farine_ble:2,champignon:3,fromage:2},output:'pizza_champignon',time:35,sell:3000,xp:150}]},
  {id:'huilerie',name:'Huilerie',emoji:'\ud83e\uded2',cost:30000,reqLevel:20,recipes:[
    {name:'Huile olive',emoji:'\ud83e\uded2',inputs:{olive:3},output:'huile_olive',time:40,sell:1000,xp:130},
    {name:'Lait coco',emoji:'\ud83e\udd65',inputs:{noix_coco:2},output:'lait_coco',time:35,sell:900,xp:110},
    {name:'Tapenade',emoji:'\ud83e\udee7',inputs:{olive:4,citron:1},output:'tapenade',time:50,sell:3500,xp:200}]},
  {id:'brasserie_tropic',name:'Brass. tropicale',emoji:'\ud83c\udf34',cost:38000,reqLevel:21,recipes:[
    {name:'Jus tropical',emoji:'\ud83c\udf79',inputs:{pasteque:2,melon:1,banane:1},output:'jus_tropical',time:20,sell:1200,xp:80},
    {name:'Punch exotique',emoji:'\ud83c\udf78',inputs:{mangue:2,noix_coco:1,citron:1},output:'punch_exotique',time:30,sell:2500,xp:150},
    {name:'Sirop piment',emoji:'\ud83c\udf36\ufe0f',inputs:{ail:2,piment:2,sucre:1},output:'sirop_piment',time:25,sell:2000,xp:120},
    {name:'Limonade past\u00e8que',emoji:'\ud83c\udf49',inputs:{pasteque:3,citron:1,sucre:1},output:'limonade_pasteque',time:22,sell:1800,xp:110}]},
  {id:'atelier_marin',name:'Atelier marin',emoji:'\ud83d\udc1a',cost:50000,reqLevel:23,recipes:[
    {name:'Collier corail',emoji:'\ud83e\udea2',inputs:{corail:3,plume_blanche:1},output:'collier_corail',time:50,sell:9000,xp:500},
    {name:'Huile tortue',emoji:'\ud83d\udc22',inputs:{carapace:2,huile_olive:1},output:'huile_tortue',time:45,sell:7000,xp:400},
    {name:'Aquarium d\u00e9co',emoji:'\ud83d\udc20',inputs:{corail:4,noix_coco:1,carapace:1},output:'aquarium_deco',time:60,sell:12000,xp:650}]},
  // ─── Tier 5 : Luxe (lv22-28) ───
  {id:'patisserie',name:'P\u00e2tisserie',emoji:'\ud83e\uddc1',cost:45000,reqLevel:22,recipes:[
    {name:'Tarte fruits',emoji:'\ud83e\udd67',inputs:{farine_ble:2,beurre:2,confiture:1,oeuf:1},output:'tarte_fruits',time:50,sell:5500,xp:300},
    {name:'Croissant',emoji:'\ud83e\udd50',inputs:{farine_ble:3,beurre:3,creme:1},output:'croissant',time:40,sell:4500,xp:250},
    {name:'Macaron',emoji:'\ud83e\uddc1',inputs:{oeuf:4,sucre:3,creme:2},output:'macaron',time:60,sell:7500,xp:400},
    {name:'Tarte citrouille',emoji:'\ud83e\udd67',inputs:{citrouille:3,farine_ble:2,oeuf:2,sucre:1},output:'tarte_citrouille',time:55,sell:1500,xp:220},
    {name:'Tarte caramel',emoji:'\ud83c\udf6e',inputs:{farine_ble:2,caramel:2,beurre:1,oeuf:1},output:'tarte_caramel',time:50,sell:6000,xp:350},
    {name:'Flan caramel',emoji:'\ud83c\udf6e',inputs:{caramel:2,lait:2,oeuf:3},output:'flan_caramel',time:45,sell:5000,xp:280},
    {name:'Tarte abricot',emoji:'\ud83c\udf51',inputs:{abricot:3,farine_ble:1,beurre:1},output:'tarte_abricot',time:45,sell:4500,xp:260},
    {name:'G\u00e2teau noix',emoji:'\ud83c\udf70',inputs:{noix:3,farine_ble:1,oeuf:2},output:'gateau_noix',time:55,sell:5500,xp:320}]},
  {id:'atelier_luxe',name:'Atelier luxe',emoji:'\ud83c\udf38',cost:55000,reqLevel:24,recipes:[
    {name:'Parfum',emoji:'\ud83c\udf38',inputs:{fleur:3,citron:2,miel:1},output:'parfum',time:60,sell:5000,xp:350},
    {name:'Bougie',emoji:'\ud83d\udd6f\ufe0f',inputs:{miel:2,fleur:2,lait_coco:1},output:'bougie',time:45,sell:2500,xp:200},
    {name:'Coussin',emoji:'\ud83d\udecb\ufe0f',inputs:{fourrure:3,plume:3,laine:2},output:'coussin',time:50,sell:1200,xp:180},
    {name:'Plumeau enchant\u00e9',emoji:'\ud83e\udeb6',inputs:{plume_blanche:3,plume_verte:2,plume_rose:2},output:'plumeau_enchante',time:55,sell:8000,xp:450},
    {name:'Potion magique',emoji:'\ud83e\uddea',inputs:{corne_magique:1,miel:2,fleur:2},output:'potion_magique',time:65,sell:15000,xp:800},
    {name:'Manteau de plumes',emoji:'\ud83e\udde5',inputs:{plume:4,plume_blanche:2,fourrure:2},output:'manteau_plumes',time:60,sell:6000,xp:380},
    {name:'Bijou corail',emoji:'\ud83d\udc8e',inputs:{corail:2,fleur:1},output:'bijou_corail',time:40,sell:5000,xp:300},
    {name:'Parfum lavande',emoji:'\ud83d\udc9c',inputs:{lavande:3,menthe:1,fleur:1},output:'parfum_lavande',time:55,sell:7000,xp:400},
    {name:'Bougie romarin',emoji:'\ud83d\udd6f\ufe0f',inputs:{romarin:2,miel:1,lait_coco:1},output:'bougie_romarin',time:45,sell:4000,xp:250},
    {name:'Sachet herbes',emoji:'\ud83c\udf3f',inputs:{lavande:2,romarin:2,menthe:2},output:'sachet_herbes',time:40,sell:5500,xp:320}]},
  {id:'chocolaterie',name:'Chocolaterie',emoji:'\ud83c\udf6b',cost:70000,reqLevel:25,recipes:[
    {name:'Chocolat',emoji:'\ud83c\udf6b',inputs:{lait_coco:2,sucre:3,beurre:2},output:'chocolat',time:50,sell:3000,xp:200},
    {name:'Pralin\u00e9s',emoji:'\ud83c\udf6c',inputs:{chocolat:2,miel:2,creme:1},output:'pralines',time:55,sell:9000,xp:500},
    {name:'Truffes',emoji:'\ud83d\udfe4',inputs:{chocolat:3,creme:2,beurre:1},output:'truffes',time:70,sell:13000,xp:650},
    {name:'Fontaine choco',emoji:'\ud83e\udd62',inputs:{chocolat:4,lait_coco:2,sucre:2},output:'fontaine_choco',time:90,sell:20000,xp:900},
    {name:'Brownie',emoji:'\ud83c\udf6b',inputs:{chocolat:2,beurre:2,oeuf:2},output:'brownie',time:45,sell:8000,xp:420},
    {name:'Mousse choco',emoji:'\ud83e\udd62',inputs:{chocolat:2,creme:3,oeuf:2},output:'mousse_choco',time:55,sell:10000,xp:550},
    {name:'Chocolat caramel',emoji:'\ud83c\udf6c',inputs:{chocolat:2,caramel:3,creme:1},output:'chocolat_caramel',time:60,sell:12000,xp:600}]},
  {id:'poissonnerie',name:'Poissonnerie',emoji:'\ud83d\udc1f',cost:80000,reqLevel:26,recipes:[
    {name:'Poisson grill\u00e9',emoji:'\ud83c\udf5d',inputs:{poisson:2,citron:1,ail:1},output:'poisson_grille',time:30,sell:3000,xp:160},
    {name:'Soupe de poisson',emoji:'\ud83c\udf72',inputs:{poisson:3,tomate:2,oignon:1,piment:1},output:'soupe_poisson',time:40,sell:5000,xp:280},
    {name:'Fish & chips',emoji:'\ud83c\udf5f',inputs:{poisson:2,patate:3,farine_ble:1},output:'fish_chips',time:35,sell:4000,xp:220},
    {name:'Bouillabaisse',emoji:'\ud83e\udd58',inputs:{poisson:4,tomate:3,champignon:2},output:'bouillabaisse',time:55,sell:7000,xp:380},
    {name:'Carpaccio marin',emoji:'\ud83e\udd61',inputs:{poisson:2,corail:1,citron:1},output:'carpaccio_marin',time:30,sell:6000,xp:340}]},
  {id:'rotisserie',name:'R\u00f4tisserie',emoji:'\ud83c\udf56',cost:90000,reqLevel:27,recipes:[
    {name:'Poulet r\u00f4ti',emoji:'\ud83c\udf57',inputs:{oeuf:5,patate:3,oignon:2,beurre:1},output:'poulet_roti',time:60,sell:8000,xp:450},
    {name:'Brochettes',emoji:'\ud83c\udf62',inputs:{viande_porc:3,oignon:2,champignon:2},output:'brochettes',time:50,sell:6500,xp:380},
    {name:'Festin dinde',emoji:'\ud83e\udd83',inputs:{roti_dinde:2,sauce_tomate:1,fromage:2,citrouille:1},output:'festin_dinde',time:80,sell:18000,xp:800},
    {name:'Gigot ail',emoji:'\ud83c\udf56',inputs:{steak:3,ail:2},output:'gigot_ail',time:65,sell:12000,xp:600},
    {name:'C\u00f4telettes',emoji:'\ud83e\udd69',inputs:{steak:2,poivron:2,oignon:1},output:'cotelettes',time:50,sell:9000,xp:480}]},
  {id:'restaurant',name:'Restaurant',emoji:'\ud83c\udf7d\ufe0f',cost:120000,reqLevel:28,recipes:[
    {name:'Menu gastro',emoji:'\ud83c\udf7d\ufe0f',inputs:{fromage:2,vin:1,huile_olive:1,farine_ble:2},output:'menu_gastro',time:70,sell:15000,xp:750},
    {name:'Festin royal',emoji:'\ud83d\udc51',inputs:{chocolat:2,vin:2,fromage:2,creme:2},output:'festin_royal',time:100,sell:28000,xp:1300},
    {name:'Banquet',emoji:'\ud83c\udf89',inputs:{confiture:2,fromage:3,vin:2,chocolat:1,huile_olive:1},output:'banquet',time:130,sell:45000,xp:2200},
    {name:'Plateau mer',emoji:'\ud83e\udd61',inputs:{poisson:2,corail:1,citron:1},output:'plateau_mer',time:60,sell:18000,xp:900},
    {name:'Thon huile',emoji:'\ud83d\udc1f',inputs:{poisson:3,huile_olive:1,ail:1},output:'thon_huile',time:50,sell:15000,xp:750},
    {name:'Entrec\u00f4te royale',emoji:'\ud83e\udd69',inputs:{steak:3,vin:1,romarin:1},output:'entrecote_royale',time:70,sell:20000,xp:1000}]},
  // ─── Tier 6 : Endgame (lv29-30) ───
  {id:'traiteur',name:'Traiteur',emoji:'\ud83c\udf69',cost:180000,reqLevel:29,recipes:[
    {name:'Tartare marin',emoji:'\ud83e\udd61',inputs:{poisson:3,citron:2,menthe:1,huile_olive:1},output:'tartare_marin',time:50,sell:22000,xp:1100},
    {name:'Festin steak',emoji:'\ud83e\udd69',inputs:{steak:3,caramel:1,vin:1,romarin:1},output:'festin_steak',time:70,sell:25000,xp:1200},
    {name:'Plat magique',emoji:'\u2728',inputs:{corne_magique:1,poisson:2,lavande:1,caramel:1},output:'plat_magique',time:80,sell:35000,xp:1800},
    {name:'Omelette g\u00e9ante',emoji:'\ud83c\udf73',inputs:{oeuf_geant:2,fromage:2,champignon:2,menthe:1},output:'omelette_geante',time:60,sell:20000,xp:1000},
    {name:'Cape prestige',emoji:'\ud83e\udde5',inputs:{plume_luxe:3,plume_blanche:2,fourrure:2,laine:3},output:'cape_prestige',time:90,sell:30000,xp:1500}]},
  {id:'palace',name:'Palace \u00e9toil\u00e9',emoji:'\ud83c\udff0',cost:250000,reqLevel:30,recipes:[
    {name:'D\u00eener royal',emoji:'\ud83d\udc51',inputs:{pizza:1,vin:2,chocolat:2,parfum:1,roti_dinde:1},output:'diner_royal',time:120,sell:60000,xp:3000},
    {name:'Buffet palace',emoji:'\ud83c\udf86',inputs:{risotto:2,smoothie:2,tarte_citrouille:1,charcuterie:2,vin:1},output:'buffet_palace',time:150,sell:80000,xp:4000},
    {name:'Gala ultime',emoji:'\ud83c\udfc6',inputs:{chocolat:3,parfum:2,vin:3,pizza:2,coussin:1,cidre:2},output:'gala_ultime',time:200,sell:150000,xp:8000},
    {name:'Banquet ultime',emoji:'\ud83c\udf1f',inputs:{poisson:3,steak:2,corne_magique:1,vin:2,caramel:2},output:'banquet_ultime',time:180,sell:120000,xp:6000},
    {name:'Festin marin royal',emoji:'\ud83d\udc51',inputs:{poisson:4,corail:2,vin:2,huile_olive:1,lavande:1},output:'festin_marin_royal',time:160,sell:100000,xp:5000}]},
  // ─── Herbes Tier : Cosm\u00e9tique, Herboristerie, D\u00e9co ───
  {id:'cosmetique',name:'Atelier Cosm\u00e9tique',emoji:'\ud83e\uddf4',cost:25000,reqLevel:16,recipes:[
    {name:'Pommade',emoji:'\ud83e\ude79',inputs:{lavande:2,miel:1},output:'pommade',time:25,sell:1500,xp:100},
    {name:'Baume \u00e0 l\u00e8vres',emoji:'\ud83d\udc8b',inputs:{menthe:2,miel:1},output:'baume_levres',time:25,sell:1400,xp:95},
    {name:'Cr\u00e8me hydratante',emoji:'\ud83e\uddf4',inputs:{verveine:2,huile_olive:1},output:'creme_hydratante',time:35,sell:2500,xp:150},
    {name:'Lotion apaisante',emoji:'\ud83d\udca7',inputs:{camomille:2,lait:1},output:'lotion_apaisante',time:30,sell:1800,xp:120},
    {name:'Masque beaut\u00e9',emoji:'\ud83e\uddd6',inputs:{romarin:2,miel:1},output:'masque_beaute',time:35,sell:2200,xp:140},
    {name:'Shampoing naturel',emoji:'\ud83e\uddf4',inputs:{romarin:2,noix_coco:1},output:'shampoing',time:30,sell:2000,xp:130},
    {name:'Gel douche',emoji:'\ud83d\udebf',inputs:{citronnelle:2,huile_olive:1},output:'gel_douche',time:35,sell:2800,xp:160},
    {name:'Savon artisanal',emoji:'\ud83e\uddfc',inputs:{sauge:2,huile_olive:1},output:'savon',time:30,sell:1600,xp:110},
    {name:'Huile de lavande',emoji:'\ud83d\udc9c',inputs:{lavande:3},output:'huile_lavande',time:40,sell:3000,xp:180},
    {name:'Huile de menthe',emoji:'\ud83c\udf3f',inputs:{menthe:3},output:'huile_menthe',time:40,sell:2800,xp:170},
    {name:'Parfum naturel',emoji:'\ud83c\udf38',inputs:{lavande:2,fleur:1},output:'parfum_naturel',time:50,sell:4000,xp:250},
    {name:'S\u00e9rum visage',emoji:'\u2728',inputs:{melisse:2,huile_olive:1},output:'serum_visage',time:45,sell:3500,xp:220}]},
  {id:'herboristerie',name:'Herboristerie',emoji:'\ud83c\udf75',cost:35000,reqLevel:18,recipes:[
    {name:'Tisane relaxante',emoji:'\u2615',inputs:{camomille:2,melisse:1},output:'tisane_relaxante',time:20,sell:2000,xp:130},
    {name:'Tisane digestive',emoji:'\ud83c\udf75',inputs:{menthe:2,thym:1},output:'tisane_digestive',time:20,sell:1800,xp:120},
    {name:'Sirop m\u00e9dicinal',emoji:'\ud83c\udf6f',inputs:{thym:2,miel:1},output:'sirop_medicinal',time:25,sell:2200,xp:140},
    {name:'Vinaigre aromatique',emoji:'\ud83e\ude97',inputs:{thym:1,vinaigre:1},output:'vinaigre_aromatique',time:20,sell:1500,xp:100},
    {name:'Pesto basilic',emoji:'\ud83c\udf3f',inputs:{basilic:3,ail:1,olive:1},output:'pesto_basilic',time:30,sell:2500,xp:160},
    {name:'Huile aromat.',emoji:'\ud83e\ded2',inputs:{origan:2,huile_olive:1},output:'huile_aromatisee',time:25,sell:2000,xp:130},
    {name:'Sel aux herbes',emoji:'\ud83e\uddc2',inputs:{thym:1,origan:1,romarin:1},output:'sel_herbes',time:20,sell:1800,xp:120},
    {name:'Sirop citronnelle',emoji:'\ud83c\udf4b',inputs:{citronnelle:2,sucre:1},output:'sirop_citronnelle',time:25,sell:2200,xp:140}]},
  {id:'deco_herbes',name:'Atelier D\u00e9co',emoji:'\ud83d\udd6f\ufe0f',cost:40000,reqLevel:20,recipes:[
    {name:'Bougie aromat.',emoji:'\ud83d\udd6f\ufe0f',inputs:{lavande:2,miel:1},output:'bougie_aromatique',time:30,sell:2500,xp:150},
    {name:'Encens',emoji:'\ud83c\udf2b\ufe0f',inputs:{sauge:2,romarin:1},output:'encens',time:35,sell:2800,xp:170},
    {name:'Sachet parfum\u00e9',emoji:'\ud83c\udf38',inputs:{lavande:2,fleur:1},output:'sachet_parfume',time:25,sell:2200,xp:140},
    {name:'Spray maison',emoji:'\ud83d\udca8',inputs:{citronnelle:2,menthe:1},output:'spray_maison',time:20,sell:1800,xp:120}]}
];
var BCOLS=6,BMAX=17,BTOTAL=100,BSTART=3;
